import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";
import { AcceptanceStatusPanel } from "@/app/components/acceptance-status-panel";

describe("acceptance status panel", () => {
  it("renders completion, verified coverage, and manual gates for Settings", () => {
    const html = renderToStaticMarkup(createElement(AcceptanceStatusPanel));

    expect(html).toContain("项目验收状态");
    expect(html).toContain("99%");
    expect(html).toContain("内部闭环可交付");
    expect(html).toContain("已由代码和测试覆盖");
    expect(html).toContain("必须人工确认");
    expect(html).toContain("内部创作闭环可交付，外部动作保留闸门");
    expect(html).toContain("可先粗略交付使用");
    expect(html).toContain("外部验收另行记录");
    expect(html).toContain("下一步安全命令");
    expect(html).toContain("完成证据");
    expect(html).toContain("必须人工验收");
    expect(html).toContain("验收证据包");
    expect(html).toContain("/api/acceptance/evidence-package · v1");
    expect(html).toContain("完成矩阵");
    expect(html).toContain("/api/acceptance/completion-matrix");
    expect(html).toContain("npm run acceptance:completion-matrix");
    expect(html).toContain("data/acceptance-completion-matrix.json");
    expect(html).toContain("机器可读的交付矩阵");
    expect(html).toContain("人工验收记录");
    expect(html).toContain("/api/acceptance/validation-records");
    expect(html).toContain("已验证 0");
    expect(html).toContain("待验证 4");
    expect(html).toContain("等待人工验收记录");
    expect(html).toContain("项目才会从 99% 变成可证明的 100%");
    expect(html).toContain("npm run acceptance:record-evidence");
    expect(html).toContain("npm run acceptance:export-records");
    expect(html).toContain("data/acceptance-validation-records-export.json");
    expect(html).toContain("npm run acceptance:evidence-package");
    expect(html).toContain("npm run acceptance:validate-evidence");
    expect(html).toContain("不会调用 MCP、模型、发布或定时任务");
    expect(html).toContain("真实发布到小红书");
    expect(html).toContain("多个真实账号切换验收");
    expect(html).toContain("Create a private visibility publish confirmation in Post Studio.");
    expect(html).toContain("证据字段");
    expect(html).toContain("Publish receipt");
    expect(html).toContain("MCP URL");
    expect(html).toContain("Verify the old publish confirmation is invalidated and a new confirmation is required.");
    expect(html).toContain("Confirmation invalidation");
    expect(html).toContain("npm run smoke:safe");
    expect(html).toContain("npm run smoke:internal-delivery");
    expect(html).toContain("docs/multi-account-acceptance.md");
  });
});
